### ISSUE TITLE
--name issue

### ISSUE THREAD

**Issue by gloria0920** [AI-sandbox/neural-admixture#13]
Hello, when I run sh run_demo.sh in linux, it will report an issue 'neural-admixture: error: the following arguments are required: --name'. When I run neural-admixture train --k 7 --data_path data/demo_data.bed --save_dir outputs --name demo_run --max_epochs 5 --seed 42 , it will have the same error... Please advice. Thanks

**Comment by AlbertDominguez** [comment]
Hello @gloria0920, could you give me info about which OS (including version and chip) you are trying to run the software on, as well as the Python version? Also, are you using `conda`/`virtualenv` or something similar?

**Comment by AlbertDominguez** [comment]
Fixed in [Release 1.1.5](https://github.com/AI-sandbox/neural-admixture/releases/tag/v1.1.5).
