### ISSUE TITLE
Error verifying vcf extensions

### ISSUE THREAD

**Issue by dasaqui** [AI-sandbox/neural-admixture#16]
When the input data_path is named using dots before the real extension like _something_._version_.vcf.gz, the actual code determines that _version_ is not a valid "vcf" extension and fails with an error.

**Comment by AlbertDominguez** [comment]
Thanks for pointing this out! Fixed in release [v1.2.2](https://github.com/AI-sandbox/neural-admixture/releases/tag/v1.2.2).
