### ISSUE TITLE
Question regarding structure of the input

### ISSUE THREAD

**Issue by mchowdh200** [AI-sandbox/neural-admixture#17]
Hi, I had a question about the nature of how the autoencoder model is applied during training/inference.

Namely, what is the dimensionality of the input x?  Is it some small fixed value?  Then is the model applied genome-wide in a sliding window fashion?

Thanks!

**Comment by AlbertDominguez** [comment]
Hi!

Thanks for your interest 🙂 The dimensionality of the input is fixed and given by the data, but is in fact not small: it is equal to the number of variants of the dataset it was trained on. The model is always applied to the whole set of SNPs at once, not in a sliding way, both during training/inference.

So, the dimensionality of the input is defined when the network is trained, and it is equal to the number of SNPs of the data.

Hope this answers your question!
