### ISSUE TITLE
Error: Ground truth ancestries needed for supervised mode

### ISSUE THREAD

**Issue by privefl** [AI-sandbox/neural-admixture#9]
I get this error when trying the `--supervised` option.
In my `.pop` file, I have some that are missing (I tried coding them with `-` or a blank line); is it not allowed to have any or should I code them differently?

**Comment by AlbertDominguez** [comment]
Hello, 

Apologies for the late response! Just noticed these issues were created.

As of now, we do not allow missing data in the `.pop` file, so in these scenarios the supervised mode should not be used. In case you wanted to run it anyway, I recommend you previously filter out the samples for which the ancestry is missing, train without them, and then run in inference mode to get the assignments for the samples for which populations are missing.

However, I think the cause of the error is the flag `--populations_path` not being specified. When calling the software in supervised mode, be sure to specify this argument with the correct path.

**Comment by Lindo007** [comment]
Hello,

I'm having the same issue with the population path in my command line:

neural-admixture --k 8 --supervised --populations_path Clade_IDs.txt --name Reference --data_path AncestryReferencePanel_Final.bed --save_dir Neural/ 

My pop file looks like this:

Clade_F
Clade_F
Clade_F
Clade_F
Clade_F
Clade_F
Clade_F
Clade_F
Clade_F
Clade_F

But I'm getting this error:

  File "/home/ec2-user/.local/lib/python3.7/site-packages/model/neural_admixture.py", line 63, in launch_training
    assert trY is not None and valY is not None, 'Ground truth ancestries needed for supervised mode'
AssertionError: Ground truth ancestries needed for supervised mode

Thanks in advance!
